config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks

  get "/:slug" => "visit#index", as: :visit
  get "/crawl/:url" => "crawl#index", as: :crawl, constraints: { url: %r{.*} }

  root to: "bookmarks#index"


end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  validates_presence_of :url, :title, :slug
  validates_uniqueness_of :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
    #prevents user from setting slug, slug picks up the first six letters of the URL
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.slug = Digest::SHA1.hexdigest(@bookmark.url)[0...6]
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:url, :title, :image, :paragraph)
    end
end

app/controllers/crawl_controller.rb
class CrawlController < ApplicationController
  def index
    url = params[:url]
    hostname = URI("http://#{url}").host

    document = Nokogiri::HTML(HTTParty.get("http://#{url}"))

    title = document.css("title").first.text
    image = document.css("img").first.attr("src") rescue nil
    paragraph = document.css("p").first.text rescue nil

    image.insert 0, "http://#{hostname}" unless image =~ /^http(s)?/

    render json: {
      title: title,
      image: image,
      paragraph: paragraph
    }
  end
end

app/controllers/visit_controller.rb
class VisitController < ApplicationController
  def index
    @bookmark = Bookmark.find_by_slug(params[:slug])
    @bookmark.increment(:visit_count)
    @bookmark.save
    redirect_to "http://" + @bookmark.url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-static-top.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse",
:type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Bookmarks", root_path, class: "navbar-brand"

    #bs-example-navbar-collaspse-1.collapse.navbar-collapse
      %ul.navbar.navbar-nav
      %ul.nav.navbar-nav.navbar-right

app/views/bookmarks/_form.html.haml
= form_for @bookmark do |f|
  - if @bookmark.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bookmark.errors.count, "error")} prohibited this bookmark from being saved:"
      %ul
        - @bookmark.errors.full_messages.each do |msg|
          %li= msg

  %p.flash.bg-danger.text-danger{"v-if": "error" } {{error}}

  %p
    = f.label :url
  %p
    = f.text_field :url, class: "form-control", "v-model": "url", "v-on:change": "urlChanged"
  %p
    = f.label :title
  %p
    = f.text_field :title, class: "form-control", "v-model": "title"

  .well
    .row
      .col-md-3
        %p(v-if="image")
          %img{"v-bind:src" => "image", :width => "100%"}
        =f.hidden_field :image, "v-model": "image"

      .col-md-9
        %p(v-if="paragraph")
          {{paragraph}}
        =f.hidden_field :paragraph, "v-model": "paragraph"
  %p
    = f.submit 'Save', class: "btn btn-primary"

app/views/bookmarks/edit.html.haml
%h1 Editing bookmark

= render 'form'

= link_to 'Show', @bookmark
\|
= link_to 'Back', bookmarks_path

app/views/bookmarks/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Url
      %th Image
      %th Title
      %th Slug
      %th Visit count
      %th

  %tbody
    - @bookmarks.each do |bookmark|
      %tr
        %td= link_to "http://" + bookmark.url, "http://" + bookmark.url
        %td= image_tag bookmark.image, width: "100" if bookmark.image
        %td
          %p
            %strong
              = bookmark.title
          %p.text-muted
            =bookmark.paragraph
        %td
          %p.input-group
            =text_field_tag "", visit_url(bookmark.slug), id: "bookmark-#{bookmark.id}", class: "form-control"
            %span.input-group-btn
              =button_tag class: "btn btn-default btn-clipboard", data: { "clipboard-target": "#bookmark-#{bookmark.id}" } do
                %i.fa.fa-clipboard
        %td= bookmark.visit_count
        %td
          = link_to 'Edit', edit_bookmark_path(bookmark)
          = link_to 'Destroy', bookmark, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bookmark', new_bookmark_path

app/views/bookmarks/new.html.haml
%h1 New bookmark

= render 'form'

= link_to 'Back', bookmarks_path

app/views/bookmarks/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @bookmark.url
%p
  %b Title:
  = @bookmark.title

= link_to 'Edit', edit_bookmark_path(@bookmark)
\|
= link_to 'Back', bookmarks_path

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Bookmarks</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body></body>
  <%= render "nav" %>
    <div class="container">
    <%= yield %>
    </div>
</html>